name: puble_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0
  flutter_switch: ^0.3.2
  email_validator: '^2.1.16'
  particles_fly: ^0.0.8
  animated_background: ^2.0.0
  flutter_markdown: ^0.6.10
  google_fonts: ^6.2.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/test2.html
